[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
ipv6 = false
prefer-ipv6 = false
icmp-auto-reply = false
always-reject-url-rewrite = false
private-ip-answer = true

# DNS settings (DIRECT queries will be resolved through specified servers at all times)
dns-server = https://cloudflare-dns.com/dns-query,https://dns.google/dns-query
dns-fallback-system = false
dns-direct-system = false
dns-direct-fallback-proxy = false
# Hijack DNS queries system-wide
hijack-dns = :53

# Return a real IP for Apple DNS queries
always-real-ip = *.apple.com,*.cdn-apple.com,*.icloud.com

[Rule]

# Block ads and trackers from resolving
RULE-SET,https://github.com/ChaCha20-Poly-1305/rule-scripting-playground/raw/refs/heads/main/ip-geo-detect-domain.list,REJECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Advertising/Advertising.list,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Advertising/Advertising_Domain.list,REJECT

# Apple system
RULE-SET,https://raw.githubusercontent.com/Luna-Repo/shadow-config/refs/heads/rules/apple.list,DIRECT

# LAN
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list,DIRECT

# Russian or affiliated websites that don't fit specified TLDs
RULE-SET,https://raw.githubusercontent.com/ChaCha20-Poly-1305/rule-scripting-playground/refs/heads/main/non-ru-TLD.list,DIRECT

# Russian TLDs and IPs (requires GeoLite2 DBs)
DOMAIN-SUFFIX,ru,DIRECT
DOMAIN-SUFFIX,su,DIRECT
DOMAIN-SUFFIX,moscow,DIRECT
DOMAIN-SUFFIX,tatar,DIRECT
DOMAIN-SUFFIX,yandex,DIRECT
DOMAIN-SUFFIX,xn--80adxhks,DIRECT
DOMAIN-SUFFIX,xn--80asehdb,DIRECT
DOMAIN-SUFFIX,xn--80aswg,DIRECT
DOMAIN-SUFFIX,xn--c1avg,DIRECT
DOMAIN-SUFFIX,xn--d1acj3b,DIRECT
DOMAIN-SUFFIX,xn--p1acf,DIRECT
DOMAIN-SUFFIX,xn--p1ai,DIRECT
GEOIP,RU,DIRECT,no-resolve
FINAL,PROXY

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^https?://(www.)?g.ru https://www.google.com 302
^https?://(www.)?google.ru https://www.google.com 302
